const fs = require("fs");
const path = require("path");
const http = require("http");
const Project = require("../models/Project");
const ProjectFile = require("../models/ProjectFile");

// Active project logs in memory
const activeProjectLogs = new Map();

// Helper to poll local Express runtime route for HTTP readiness
async function waitForHttpReadiness(url, maxTimeoutMs = 5000, intervalMs = 200) {
  const startTime = Date.now();

  return new Promise((resolve, reject) => {
    const attempt = () => {
      if (Date.now() - startTime > maxTimeoutMs) {
        return reject(new Error(`Timeout (${maxTimeoutMs}ms) waiting for Express runtime route at ${url}`));
      }

      const req = http.get(url, (res) => {
        res.resume();
        if (res.statusCode >= 200 && res.statusCode < 400) {
          resolve(true);
        } else {
          setTimeout(attempt, intervalMs);
        }
      });

      req.on("error", () => {
        setTimeout(attempt, intervalMs);
      });

      req.end();
    };

    attempt();
  });
}

// Materialize project files from MongoDB onto local disk in backend/runtime-projects/<projectId>/
async function materializeProjectFiles(projectId) {
  const targetDir = path.join(__dirname, "..", "runtime-projects", String(projectId));

  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }

  const files = await ProjectFile.find({ projectId });
  if (!files || files.length === 0) {
    throw new Error("No generated project files found. Run Swarm agents first.");
  }

  let hasIndexHtml = false;

  for (const file of files) {
    let relPath = file.filePath || file.fileName;
    // Strip leading public/ or src/ prefix for flat web runtime access if present
    if (relPath.startsWith("public/")) {
      relPath = relPath.replace(/^public\//, "");
    }
    const fullPath = path.join(targetDir, relPath);
    const fileDir = path.dirname(fullPath);

    if (!fs.existsSync(fileDir)) {
      fs.mkdirSync(fileDir, { recursive: true });
    }

    fs.writeFileSync(fullPath, file.content || "", "utf8");

    if (relPath === "index.html" || file.fileName === "index.html") {
      hasIndexHtml = true;
    }
  }

  // Ensure index.html exists
  const indexPath = path.join(targetDir, "index.html");
  if (!fs.existsSync(indexPath) || !hasIndexHtml) {
    const project = await Project.findById(projectId);
    const title = project?.title || "SwarmOS Application";
    const desc = project?.description || "Generated by SwarmOS AI Agent Team";

    const defaultHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title} — Powered by SwarmOS</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body style="background:#09090b; color:#f4f4f5; font-family:-apple-system, sans-serif; padding:24px;">
  <div style="max-width:900px; margin:0 auto; background:#18181b; border:1px solid #27272a; padding:32px; border-radius:16px;">
    <h1 style="color:#06b6d4; margin-top:0;">📚 ${title}</h1>
    <p style="color:#a1a1aa;">${desc}</p>
    <hr style="border:0; border-top:1px solid #27272a; margin:20px 0;">
    <div style="display:grid; grid-template-columns:repeat(3, 1fr); gap:16px;">
      <div style="background:#09090b; padding:16px; border-radius:12px; border:1px solid #27272a;">
        <span style="color:#a1a1aa; font-size:12px;">STATUS</span>
        <h3 style="color:#10b981; margin:8px 0 0 0;">ACTIVE MVP</h3>
      </div>
      <div style="background:#09090b; padding:16px; border-radius:12px; border:1px solid #27272a;">
        <span style="color:#a1a1aa; font-size:12px;">ENGINE</span>
        <h3 style="color:#06b6d4; margin:8px 0 0 0;">SWARMOS</h3>
      </div>
      <div style="background:#09090b; padding:16px; border-radius:12px; border:1px solid #27272a;">
        <span style="color:#a1a1aa; font-size:12px;">PORT</span>
        <h3 style="color:#3b82f6; margin:8px 0 0 0;">5000</h3>
      </div>
    </div>
  </div>
</body>
</html>`;
    fs.writeFileSync(indexPath, defaultHtml, "utf8");
  }

  // Ensure styles.css exists
  const stylesPath = path.join(targetDir, "styles.css");
  if (!fs.existsSync(stylesPath)) {
    const defaultCss = `body { background: #09090b; color: #f4f4f5; font-family: -apple-system, sans-serif; margin: 0; padding: 24px; }`;
    fs.writeFileSync(stylesPath, defaultCss, "utf8");
  }

  // Ensure package.json exists
  const pkgPath = path.join(targetDir, "package.json");
  if (!fs.existsSync(pkgPath)) {
    const pkgJson = {
      name: `swarmos-project-${projectId}`,
      version: "1.0.0",
      description: "SwarmOS AI Generated Web Application",
      main: "index.html",
    };
    fs.writeFileSync(pkgPath, JSON.stringify(pkgJson, null, 2), "utf8");
  }

  return { targetDir, filesCount: files.length };
}

// Run project — Materializes files to backend/runtime-projects/<projectId>/ and serves via Express
async function runProject(projectId) {
  const project = await Project.findById(projectId);
  if (!project) throw new Error("Project not found");

  project.runtimeStatus = "starting";
  project.runtimeError = "";
  await project.save();

  const logs = [];
  const addLog = (msg, level = "info") => {
    const entry = `[${new Date().toLocaleTimeString()}] ${msg}`;
    logs.push(entry);
    if (logs.length > 200) logs.shift();

    project.executionLogs.push({
      agentName: "Orchestrator",
      level,
      message: msg,
    });
  };

  addLog("Starting project...");
  addLog("Preparing generated project files...");

  try {
    const { targetDir } = await materializeProjectFiles(projectId);

    const runtimePort = Number(process.env.PORT || 5000);
    const runtimeUrl = `http://localhost:${runtimePort}/runtime/${projectId}/`;

    addLog(`Materialized project files to runtime-projects/${projectId}`);
    addLog(`Verifying Express runtime endpoint at ${runtimeUrl}...`);

    // Verify local Express route HTTP response
    await waitForHttpReadiness(runtimeUrl, 5000);

    addLog("Application responded successfully with HTTP 200.", "success");
    addLog(`Project is running at ${runtimeUrl}`, "success");

    project.runtimeStatus = "running";
    project.runtimePort = runtimePort;
    project.runtimeUrl = runtimeUrl;
    project.runtimeStartedAt = new Date();
    project.runtimeError = "";
    await project.save();

    activeProjectLogs.set(String(projectId), logs);

    return {
      status: "running",
      port: runtimePort,
      url: runtimeUrl,
      startedAt: project.runtimeStartedAt,
      logs,
    };
  } catch (error) {
    addLog(`[ERR] Runtime activation failed: ${error.message}`, "error");

    project.runtimeStatus = "failed";
    project.runtimeError = error.message;
    project.runtimeUrl = "";
    await project.save();

    throw new Error(`Project failed to start: ${error.message}`);
  }
}

// Stop running project — Disables runtime directory access
async function stopProject(projectId) {
  const project = await Project.findById(projectId);
  const targetDir = path.join(__dirname, "..", "runtime-projects", String(projectId));

  if (fs.existsSync(targetDir)) {
    try {
      fs.rmSync(targetDir, { recursive: true, force: true });
    } catch (e) {
      console.warn("Notice removing runtime directory:", e.message);
    }
  }

  activeProjectLogs.delete(String(projectId));

  if (project) {
    project.runtimeStatus = "stopped";
    project.runtimePort = 0;
    project.runtimeUrl = "";

    project.executionLogs.push({
      agentName: "Orchestrator",
      level: "info",
      message: "■ Project runtime stopped by user",
    });

    await project.save();
  }

  return { status: "stopped" };
}

// Get runtime state & logs
async function getRuntimeState(projectId) {
  const project = await Project.findById(projectId).select(
    "runtimeStatus runtimePort runtimeUrl runtimeStartedAt runtimeError deploymentStatus deploymentUrl deploymentError"
  );

  const targetDir = path.join(__dirname, "..", "runtime-projects", String(projectId));
  const isRuntimeActive = fs.existsSync(targetDir);

  return {
    status: project?.runtimeStatus || "idle",
    port: project?.runtimePort || 0,
    url: project?.runtimeUrl || "",
    startedAt: project?.runtimeStartedAt || null,
    error: project?.runtimeError || "",
    deploymentStatus: project?.deploymentStatus || "not_configured",
    deploymentUrl: project?.deploymentUrl || "",
    deploymentError: project?.deploymentError || "",
    isProcessAlive: isRuntimeActive,
  };
}

// Get runtime logs
function getRuntimeLogs(projectId) {
  const logs = activeProjectLogs.get(String(projectId));
  return logs || ["No active runtime logs available."];
}

module.exports = {
  materializeProjectFiles,
  runProject,
  stopProject,
  getRuntimeState,
  getRuntimeLogs,
};
